name: Hello World Series

on:
  workflow_dispatch:

jobs:
  just-say-hello:
    runs-on: macos-26
    steps:
      - run: echo "Hello, Hello! from an inline bash script in a GitHub Action Workflow on Mac!"
      -run: ps
      

    
