name: Hello World Series

on:
  push: 
    branches: 
      - "main"
  pull_request: 
    types: 
      - opened
      - synchronize
      - reopened
    paths: 
      - "!03-core-features/filters/*.md"
      - "03-core-features/filters/*.txt"

jobs:
  just-say-hello:
    runs-on: macos-26
    steps:
      - name: Setting Variable
        run: 
          my_var="Hello World! with CLI pull origin my test branch";
          echo $my_var
          
  say-hello-in-python:
    runs-on: macos-26
    steps:
      - run: print("Hello world from python!")
        shell: python
    needs: 
      - just-say-hello


    
